# Generated by Django 4.0 on 2022-03-13 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_grade_demo_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
